### ISSUE TITLE
Interface of the webpage needs a lot of improvement not set up properly but just some random html commads were used

### ISSUE THREAD

**Issue by saxena-vinayak36** [RuanAragao/calculator#1]

**Comment by saxena-vinayak36** [comment]
if this is for hacktoberfest can i solve this for you

**Comment by RuanAragao** [comment]
@saxena-vinayak36 create an issue more organized with you propose and I sign to you.

**Comment by Ratikant-rout** [comment]
@saxena-vinayak36 Can You Please Assign Me This Issue I want To Fix It.

**Comment by Rajeevjewar** [comment]
Yeah First of all we have to design it with some tools like Figma or AdobeXD then we can proceed to code.
