### ISSUE TITLE
Complex Number Calculator

### ISSUE THREAD

**Issue by Dhandeep10** [RuanAragao/calculator#103]
Calculate operations on complex numbers; including addition, subtraction, multiplication, and division.
please assign me this under hacktober fest.

**Comment by Dhandeep10** [comment]
@RuanAragao please assign me this

**Comment by Dhandeep10** [comment]
@RuanAragao 
can you please assign this, as hacktoberfest's deadline is approaching

**Comment by RuanAragao** [comment]
> @RuanAragao can you please assign this, as hacktoberfest's deadline is approaching

Hello, you don't need to wait for the assignment and label to start work or submit the PR. We cannot provide support all the time, it is an asynchronous process. It is even something that is in the contribution documents linked in the README. I highly recommend reading everything there, as the main purpose of this repository is to develop skills for teamwork and contributions to projects in general. Hugs!
