### ISSUE TITLE
Scientific Calculator

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [RuanAragao/calculator#12]
I want to add Scientific calculator which contains ,

**addition , subtraction ,multiplication , division , square root , factorial , square , Log , ln , sin , cos , tan** etc ;

assign this to me , I am interested to contribute myself in hacktoberfest_2023 : )

**Comment by Bharath-KumarReddy** [comment]
Here is the demo ------------------------> 

https://github.com/RuanAragao/calculator/assets/127650446/40c6dc07-d892-4b6c-a2fd-9cae2574abff

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I resolved this issue once check the PR #17

**Comment by TusharRastogi04** [comment]
hi @RuanAragao can you please assign this issue to me as it looks a goodfit for my field
