### ISSUE TITLE
Adding a BMI calculator 

### ISSUE THREAD

**Issue by sanket2323** [RuanAragao/calculator#15]

**Comment by Ratikant-rout** [comment]
hii @Sanketmane2323 Can You Assign me This Issue I Want To Make Such Calculator Projects And I Want To Contribute to it As Well.

**Comment by Sanketmane2323** [comment]
Hey @Ratikant-rout 
I will add the BMI Calculator and then u can make the required changes in it.

**Comment by Ratikant-rout** [comment]
Okk @Sanketmane2323 NO Issues
