### ISSUE TITLE
Missing Favicon for Mobile, Tab, and Website

### ISSUE THREAD

**Issue by Rajeevjewar** [RuanAragao/calculator#2]
I have identified that our project is currently lacking a favicon, which is an essential design element. I kindly request the implementation of a favicon for mobile, tab, and website to enhance the overall user experience. Your attention to this matter is greatly appreciated. Thank you.

**Comment by RuanAragao** [comment]
> I have identified that our project is currently lacking a favicon, which is an essential design element. I kindly request the implementation of a favicon for mobile, tab, and website to enhance the overall user experience. Your attention to this matter is greatly appreciated. Thank you.

I assigned to you. Thanks!

**Comment by RuanAragao** [comment]
Soved on #7
