### ISSUE TITLE
Making the Index UI better

### ISSUE THREAD

**Issue by ayushsgit** [RuanAragao/calculator#34]
I want to make the Index UI of this site i.e. where all the calculators are displayed better for user

**Comment by ayushsgit** [comment]
![image](https://github.com/RuanAragao/calculator/assets/115374687/7728618a-dd3a-4a84-b377-5bcb46494958)
How about this? If need some changes please tell me
If its good to go I will do a PR

**Comment by Atheke** [comment]
I would also like to contribute to this issue

**Comment by RuanAragao** [comment]
@ayushsgit firstly, congratulations on the work. 

1. I believe softer colors would look a little better in this case. 
2. The font of the title may continue to be more ornate, but the font of the links would be better with a more readable one.

I think removing the background, border and shadow colors from the header would look cool. But it's just a tip.

**Comment by ayushsgit** [comment]
![image](https://github.com/RuanAragao/calculator/assets/115374687/e0fd314e-74ea-493a-b31d-5a3926e48658)
what about this?  If further changes are required just let me know

**Comment by RuanAragao** [comment]
> ![image](https://user-images.githubusercontent.com/115374687/277145337-e0fd314e-74ea-493a-b31d-5a3926e48658.png) what about this? If further changes are required just let me know

Is well. Open the PR. Thanks!
