### ISSUE TITLE
Adding Currency Calculator USD to INR 

### ISSUE THREAD

**Issue by Sameersawant77** [RuanAragao/calculator#5]
Assign me this issue with a hacktoberfest label, would love to contribute

**Comment by Rajeevjewar** [comment]
This design might be helpful for contributors 👇

<img width="276" alt="Screenshot 2023-10-20 at 12 59 53 AM" src="https://github.com/RuanAragao/calculator/assets/97542658/1f1e8474-89a9-4b19-a423-ff2030e19fd0">

But try to choose the color yellow to keep the design consistent. I am working on its design.

The color of the button or the graph image should be this `#F9980B`.
