### ISSUE TITLE
Temperature Calculator Not Working

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [RuanAragao/calculator#51]
- Temperature calculator not working as expected.
- UI/UX is not very good.

![image](https://github.com/RuanAragao/calculator/assets/114330097/51b10486-fc7a-4ac7-878a-175be1ae9a35)

- Adding the functioning and removing the errors.
- Make an attractive UI/ UX for the temperature calculator.
- Hover effect and fluid effect on the button.
- Good font style and font size.

**Comment by Avdhesh-Varshney** [comment]
@RuanAragao please assign this task to me to contribute it under hacktoberfest 2023

**Comment by Rajeevjewar** [comment]
Hey @Avdhesh-Varshney, Are you still working on this issue.
