### ISSUE TITLE
Improve the UI of home page by converting the text into buttons.

### ISSUE THREAD

**Issue by ch-sohan** [RuanAragao/calculator#56]
Users feel more comfortable on clicking the buttons rather than clicking the text that is hyperlinked to other webpages. 
Please assign me this task under hactoberfest2023.
Thank you.

**Comment by Rajeevjewar** [comment]
Hello @ch-sohan, I am working on its design and I had completed its header and now working on its hero and other important sections.
So please assign this issue to me.
