### ISSUE TITLE
I can  user friendly User Interface for you

### ISSUE THREAD

**Issue by Radhey644** [RuanAragao/calculator#73]
The site you have made is not user frienldy and attractive i can make it more atractive and user friendly so that any user finds it more appealing to use.

**Comment by Radhey644** [comment]
@RuanAragao pls look under my concern.

**Comment by RuanAragao** [comment]
@Radhey644 Do you have a mockup of the proposal?

**Comment by Radhey644** [comment]
yes,I will provide it to you if you give me some time.
and i request you to put my project under the hacktoberfest.
