### ISSUE TITLE
Adding Temperature Calculator Celsius to Kelvin to Fahrenheit.

### ISSUE THREAD

**Issue by Rajeevjewar** [RuanAragao/calculator#8]
Add a temperature Calculator which converts Celsius to Kelvin to Fahrenheit.

Please keep in mind design should look like this 👇

<img width="276" alt="Screenshot 2023-10-20 at 12 59 53 AM" src="https://github.com/RuanAragao/calculator/assets/97542658/8accc0f5-68ba-4261-906c-2ec7828419b8">

**Comment by JonasRafael16** [comment]
I would like to contribute to the project, can you sign for me?

**Comment by 29deepanshutyagi** [comment]
kindly assign me this issue @RuanAragao , i want to work on this issue
