### ISSUE TITLE
Binary Operations Calculator 

### ISSUE THREAD

**Issue by devxiexie** [RuanAragao/calculator#94]
Title: 
Binary Operations Calculator 

Description:
Calculates binary operations, like bitwise and, bitwise or, and also adds, subtracts, and multiplies.

**Comment by kahenya-anita** [comment]
Hi @RuanAragao @devxiexie I would like to work on this

**Comment by devxiexie** [comment]
Hey @kahenya-anita, I’m working on this issue already :)! If you have an idea for a calculator, you need to make your own issue, like the readme says.
