### ISSUE TITLE
School Calculator

### ISSUE THREAD

**Issue by harshitadharamansharma** [RuanAragao/calculator#98]
The general calculator performs the following operations

1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Percentage 

in the Decimal Number System.

**Comment by harshitadharamansharma** [comment]
Please tag these issues under the fest and assign them to me.

**Comment by harshitadharamansharma** [comment]
can you please help me, as I'm not able to make a PR in your Repo? Why is this happening? 

![image](https://github.com/RuanAragao/calculator/assets/79998309/54d5a08b-c7d3-4bf4-886a-8be544c26fc7)

**Comment by RuanAragao** [comment]
> can you please help me, as I'm not able to make a PR in your Repo? Why is this happening?
> 
> ![image](https://user-images.githubusercontent.com/79998309/278825495-bb8f2acf-238e-40d3-9909-27af2109407d.png)

Select the base: main

**Comment by harshitadharamansharma** [comment]
Thanks @RuanAragao. Please check the request.

**Comment by harshitadharamansharma** [comment]
Please check the PR.
